import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ProfileLayout from './components/layout/profileLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hello, i am Chuyen',
  description: 'Generated by Chuyendev',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="en">
      <body className='h-screen overflow-y-scroll'><ProfileLayout>{children}</ProfileLayout></body>
    </html>
  )
}
